### ISSUE TITLE
Fix the following failed assertions/BSODs/etc.

### ISSUE THREAD

**Issue by Zero3K** [Zero3K/reactos#1]
*subject*

[irp_bug_driver_verifier_udfs (1).log](https://github.com/Zero3K/reactos/files/12457819/irp_bug_driver_verifier_udfs.1.log)
[irp_bug_driver_verifier_udfs_2.log](https://github.com/Zero3K/reactos/files/12457828/irp_bug_driver_verifier_udfs_2.log)
![image (18)](https://github.com/Zero3K/reactos/assets/6194332/4b612902-dcdd-4bec-9bce-52237284958c)
![image (17)](https://github.com/Zero3K/reactos/assets/6194332/9083267e-46ab-48c8-9c1c-2c2417ff18d4)
![image (16)](https://github.com/Zero3K/reactos/assets/6194332/eb4a1300-5107-441d-af6d-87672718dba8)
![image (15)](https://github.com/Zero3K/reactos/assets/6194332/baaab96c-0a03-415a-8381-16bcdec71599)
![image (14)](https://github.com/Zero3K/reactos/assets/6194332/0fc95915-e9e6-443d-91c5-7d1ea0423941)
![image (13)](https://github.com/Zero3K/reactos/assets/6194332/1cea2679-597e-41de-8f96-8d8b215185be)
![image (12)](https://github.com/Zero3K/reactos/assets/6194332/3b09c2b2-0d04-4c29-8313-d5d03fb5af02)
[irp_bug_driver_verifier_udfs.log](https://github.com/Zero3K/reactos/files/12457831/irp_bug_driver_verifier_udfs.log)
[secondsight_write_issues_udf_win2k3.log](https://github.com/Zero3K/reactos/files/12457832/secondsight_write_issues_udf_win2k3.log)
[udfs-assertions (3).txt](https://github.com/Zero3K/reactos/files/12457837/udfs-assertions.3.txt)
[windows11_udfs_bsod.log](https://github.com/Zero3K/reactos/files/12457841/windows11_udfs_bsod.log)
[windows11_udfs_driver_verifier.log](https://github.com/Zero3K/reactos/files/12457842/windows11_udfs_driver_verifier.log)

**Comment by Zero3K** [comment]
They are happening when using the driver compiled from the udf branch.

**Comment by Zero3K** [comment]
Also, please get it to support reading and writing of UDF 2.50 formatted drives.

**Comment by abebeos** [comment]
> They are happening when using the driver compiled from the udf branch.

@Zero3K , questions:

- happens for both build environments (RosBE / VS CPP) ?
- have you inspected the relevant "FileInfo" and "FileInfor->Dloc->DataLoc.Mapping" to get hints for the root-cause?
  - ideally provide those Data visualizations from the debugger watch

**Comment by Zero3K** [comment]
I am closing this because I have someone who is fixing the bugs in it. You can see his progress at https://github.com/assorted/reactos/commits/udf.
